package:
  name: msight
  version: "1.0.0"

source:
  path: ..

build:
  noarch: python
  script: python setup.py install

requirements:
  build:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - matplotlib==3.7.2
    - numpy==1.24.4
    - pandas==1.5.3
    - plotly==5.22.0
    - pytest==8.2.2
    - scipy==1.10.1
    - seaborn==0.11.2
    - SimpleITK==2.4.0
    - tifffile==2023.4.12
    - sphinx_rtd_theme==1.0.0
    - notebook==7.3.1
    - jupyter_server==2.14.2



about:
  home: https://github.com/laurenfields/MSIght_1.0.0
  license: MIT
  license_file: LICENSE
  summary: "Mass Spectrometry Imaging and Analysis Tools."

extra:
  recipe-maintainers:
    - lafields2
